Not using CodecSupported() API from rocDecode if ROCM version less than 6.3
ROCm/rocPyDecode pull request #105
Opened 2024-10-01 16:04 UTC by essamROCm

Avoid any build issues when build against ROCm 6.2.2 or less, when build with 6.3 or higher no issues.

2024-10-01 17:28 UTC, AryanSalmanpour requested changes

2024-10-01 17:28 UTC, AryanSalmanpour commented on src/roc_pyvideodecode.cpp
> +#if defined(HIP_VERSION_MINOR) && HIP_VERSION_MINOR < 3
Please use the `ROCDECODE_CHECK_VERSION` to check the rocDecode version. This macro already exists in ROCm 6.3. The current version of the rocDecode in am-mainline is 0.7.0.

2024-10-01 20:22 UTC, essamROCm commented on src/roc_pyvideodecode.cpp
> +#if defined(HIP_VERSION_MINOR) && HIP_VERSION_MINOR < 3
Used in the last commit: https://github.com/ROCm/rocPyDecode/pull/105/commits/b03d3f22ea76f9784000d3975763f167077dde45

2024-10-02 12:37 UTC, AryanSalmanpour approved these changes

2024-10-02 20:28 UTC, rrawther approved these changes

2024-10-02 22:17 UTC, merged