Samples using rocDecode package videos instead of rocPyDecode
ROCm/rocPyDecode pull request #117
Opened 2024-10-09 21:49 UTC by essamROCm

To avoid adding the video sub folder into the wheel, using the rocDecode package videos instead, changes made in files to reflect that.

2024-10-28 16:27 UTC, AryanSalmanpour requested changes

2024-10-28 16:27 UTC, AryanSalmanpour commented on samples/CMakeLists.txt
> +            -i /opt/rocm/share/rocdecode/video/AMD_driving_virtual_20-H265.mp4
Please add the following code at the top of this CMakeLists.txt file for setting the ROCM_PATH 

```
# ROCM Path
if(DEFINED ENV{ROCM_PATH})
  set(ROCM_PATH $ENV{ROCM_PATH} CACHE PATH "${White}${PROJECT_NAME}: Default ROCm installation path${ColourReset}")
elseif(ROCM_PATH)
  message("-- ${White}${PROJECT_NAME} :ROCM_PATH Set -- ${ROCM_PATH}${ColourReset}")
else()
  set(ROCM_PATH /opt/rocm CACHE PATH "${White}${PROJECT_NAME}: Default ROCm installation path${ColourReset}")
endif()
```

then use `${ROCM_PATH}/share/rocdecode/video` instead of `/opt/rocm/share/rocdecode/video/`

2024-10-28 16:41 UTC, essamROCm commented on samples/CMakeLists.txt
> +            -i /opt/rocm/share/rocdecode/video/AMD_driving_virtual_20-H265.mp4
Done in latest: https://github.com/ROCm/rocPyDecode/pull/117/commits/badaa82340759e12a1b1e30a3c97f2f337a44c68

2024-10-28 16:44 UTC, AryanSalmanpour requested changes

2024-10-28 16:44 UTC, AryanSalmanpour commented on samples/CMakeLists.txt
> +            -i /${ROCM_PATH}/share/rocdecode/video/AMD_driving_virtual_20-H265.mp4
please remove the extra `/` before `${ROCM_PATH}`

2024-10-28 16:52 UTC, essamROCm commented on samples/CMakeLists.txt
> +            -i /${ROCM_PATH}/share/rocdecode/video/AMD_driving_virtual_20-H265.mp4
Removed

2024-10-28 20:53 UTC, LakshmiKumar23 approved these changes

2024-10-28 20:53 UTC, rrawther approved these changes

2024-10-30 18:51 UTC, AryanSalmanpour approved these changes

2024-10-30 20:41 UTC, merged