Enabling FFMpegVideoDecoder new class provider with new python sample
ROCm/rocPyDecode pull request #141
Opened 2024-12-14 19:02 UTC by essamROCm

FFMpegVideoDecoder new class is enabled, and used in a new python sample as a cpu backend decoder.

2025-01-14 19:38 UTC, rrawther commented on samples/videodecode_cpu_backend.py
> +        b_generate_md5,
I think we don't really need to expose md5 functionality in this sample

2025-01-14 20:04 UTC, essamROCm commented on samples/videodecode_cpu_backend.py
> +        b_generate_md5,
Removed in this commit: https://github.com/ROCm/rocPyDecode/pull/141/commits/58a6656920e50dcc61745c5284f62cbdf9a4dd27

2025-01-17 18:52 UTC, rrawther requested changes
Added few comments

2025-01-17 18:52 UTC, rrawther commented on samples/videodecodetorch_cpu_backend.py
> +    b_force_zero_latency = args.zero_latency.upper()
this is not supported in the software based decoder

2025-01-18 21:02 UTC, essamROCm commented on samples/videodecodetorch_cpu_backend.py
> +    b_force_zero_latency = args.zero_latency.upper()
Removed all latency options in the samples here: https://github.com/ROCm/rocPyDecode/pull/141/commits/d4f7f2624dfbd0927060f2e72710aa28fb57137f

2025-01-23 17:05 UTC, essamROCm commented
Hi @kiritigowda @AryanSalmanpour 
Can you please merge this PR, or review/approve so I can merge it?
Thank you.

2025-01-23 19:01 UTC, rrawther approved these changes

2025-01-23 19:17 UTC, merged