Adding rst API docs
ROCm/rocPyDecode pull request #80
Opened 2024-08-26 20:47 UTC by essamROCm

Adding all the RST files for the rocPyDecode API

2024-08-26 22:28 UTC, randyh62 approved these changes

2024-08-26 22:28 UTC, randyh62 commented on docs/reference/rocPyDecode.rst
> +The rocPyDecode API main classes are a decoder class and a demuxer class. All rocPyDecode APIs are exposed using the header files ``decoder.py`` and ``demuxer.py``. You can find these files in the `p
The decoder and demuxer classes seem related to the ``PyRocVideoDecoder`` and ``PyVideoDemuxer`` classes discussed in the _Using rocPyDecode_ topic. If these are the same then we should sort out the naming of these classes. It looks like the functions are similar, though there are some differences.

2024-08-27 13:57 UTC, essamROCm commented on docs/reference/rocPyDecode.rst
> +The rocPyDecode API main classes are a decoder class and a demuxer class. All rocPyDecode APIs are exposed using the header files ``decoder.py`` and ``demuxer.py``. You can find these files in the `p
The 'Py' prefixed classes inherit base functionality, that are performed in C++ LIB space, however they are different in that they expose different interface to appropriately support those functionalities inside the Python space. The naming starts with prefix 'Py' indicate that they are specially placed in the Python space, while the original name without 'Py' indicate that they live in the C++ space.

2024-08-27 14:10 UTC, randyh62 commented on docs/reference/rocPyDecode.rst
> +The rocPyDecode API main classes are a decoder class and a demuxer class. All rocPyDecode APIs are exposed using the header files ``decoder.py`` and ``demuxer.py``. You can find these files in the `p
Maybe worth adding to either the Using rocPyDecode topic or Reference topic?

2024-08-27 20:19 UTC, rrawther commented on docs/data/reference/rocPyDecodeArch.png
I think we need to change the color of the arrows for this picture as it is not visible in the white background. Also I feel the perforated background window is not looking good as well

2024-08-27 20:22 UTC, rrawther commented on docs/reference/deCoderClass.rst
typo "deCoderClass" please change to decoderClass.rst

2024-08-27 20:23 UTC, rrawther commented on docs/reference/deCoderClass.rst
> +^^^^^^^^
please be consistent in underlining format. previous is "----"

2024-08-27 20:24 UTC, rrawther commented on docs/reference/deMuxerClass.rst
same here. demuxerClass.rst is correct name

2024-08-27 20:27 UTC, rrawther commented on docs/reference/deMuxerClass.rst
> +		seek_frame = 100     # seek 100 frames
change comment to "seek to 100th frame"

2024-08-27 20:29 UTC, rrawther requested changes
added review comments

2024-08-27 20:40 UTC, randyh62 commented on docs/reference/deCoderClass.rst
> +^^^^^^^^
These are header levels: 
===== is H1, ----- is H@, and ^^^^ is H4 level headers

2024-08-29 18:57 UTC, essamROCm commented on docs/reference/rocPyDecode.rst
> +The rocPyDecode API main classes are a decoder class and a demuxer class. All rocPyDecode APIs are exposed using the header files ``decoder.py`` and ``demuxer.py``. You can find these files in the `p
> Maybe worth adding to either the Using rocPyDecode topic or Reference topic?

Can you please explain this request in teams? I cannot get it from the question here.

2024-09-03 15:24 UTC, essamROCm commented on docs/reference/rocPyDecode.rst
> +The rocPyDecode API main classes are a decoder class and a demuxer class. All rocPyDecode APIs are exposed using the header files ``decoder.py`` and ``demuxer.py``. You can find these files in the `p
Per our conversation, I added more explanation to clarify [here in this last commit](https://github.com/ROCm/rocPyDecode/pull/80/commits/73c55c95eb060ee05fd24c276e53d8e3a935144e).

2024-09-06 18:21 UTC, kiritigowda approved these changes

2024-09-06 18:22 UTC, merged