Fixing build error message that shows "No module named pip"
ROCm/rocPyDecode pull request #86
Opened 2024-09-13 00:39 UTC by essamROCm

Moving 2 lines from CMakeLists.txt to rocPyDecode-requirements.py to avoid build errors that says No module named pip

2024-09-24 14:08 UTC, AryanSalmanpour requested changes

2024-09-24 14:08 UTC, AryanSalmanpour commented on rocPyDecode-requirements.py
> +ERROR_CHECK(os.system('python3 -m pip install -i https://test.pypi.org/simple hip-python'))
Hip-python is not a requirement for core rocPyDecode. It is only needed for the perf sample. Please remove it from here and leave it as a dependency for samples only. Thanks.

2024-09-24 14:08 UTC, AryanSalmanpour commented on samples/CMakeLists.txt
> +    #execute_process(COMMAND ${Python3_EXECUTABLE} -m pip install --upgrade pip)
Please remove this commented-out line as it is moved to rocPyDecode-requirements.py.

2024-09-24 14:08 UTC, AryanSalmanpour commented on samples/CMakeLists.txt
> +    #execute_process(COMMAND ${Python3_EXECUTABLE} -m pip install -i https://test.pypi.org/simple hip-python)
As mentioned above, the hip-python should remain here as it is only needed for the perf sample.

2024-09-25 02:21 UTC, LakshmiKumar23 commented on rocPyDecode-requirements.py
> +ERROR_CHECK(os.system('python3 -m pip install --upgrade pip'))
Not sure we need this either. We already install python3-pip on this line https://github.com/ROCm/rocPyDecode/blob/b29262f3132beb74ffd46ff34ec4732f50d30be1/rocPyDecode-requirements.py#L134. So that should bring the latest

2024-10-03 18:41 UTC, closed without merging