Add GetBitDepth for decoder & use this to set dtype for dlpack
ROCm/rocPyDecode pull request #90
Opened 2024-09-18 03:56 UTC by LakshmiKumar23

2024-09-18 15:05 UTC, jeffqjiangNew requested changes

2024-09-18 15:05 UTC, jeffqjiangNew commented on src/roc_pybuffer.cpp
> +        m_dlTensor->dtype.code = kDLInt;  // TODO: add support for 12-bit when required
We should use unsigned integer type kDLUInt, same as 8 bit.

2024-09-18 15:05 UTC, jeffqjiangNew commented on src/roc_pybuffer.cpp
>      int itemSizeDT = sizeof(uint8_t);
This is hard coded and needs review. Lets discuss offline along with the stride changes.

2024-09-18 15:25 UTC, essamROCm commented on src/roc_pybuffer.cpp
>      int itemSizeDT = sizeof(uint8_t);
There are multiple places in the source code that the change of the uint8 to any size will have an impact, such as when copying the actual frame data based on each element size, 8 or 16 bit, eyc. 

Also, the LoadDlPack copying of a frame is currently assume NV12 plane order, must also support YUV444 and P016 plane order.

2024-09-18 15:29 UTC, essamROCm commented on src/roc_pybuffer.cpp
> +        m_dlTensor->dtype.code = kDLInt;  // TODO: add support for 12-bit when required
Any change in the bit depth, as it has repel-effect in the code, must be tested eventually by saving the tensor in the python example, and visually examine it.

2024-09-18 16:11 UTC, LakshmiKumar23 commented on src/roc_pybuffer.cpp
> +        m_dlTensor->dtype.code = kDLInt;  // TODO: add support for 12-bit when required
We tested this with a 10bit video and visually looked at it. It looks good. I have handled the bit sizes across all places where it occurs

2024-09-18 16:12 UTC, LakshmiKumar23 commented on src/roc_pybuffer.cpp
>      int itemSizeDT = sizeof(uint8_t);
Pushing a change for the itemSize in my next commit and handling stride accordingly

2024-09-18 23:53 UTC, AryanSalmanpour requested changes

2024-09-18 23:53 UTC, AryanSalmanpour commented on src/roc_pybuffer.cpp
> +    if (m_dlTensor->dtype.code == kDLUInt && m_dlTensor->dtype.bits == 8)
remove `m_dlTensor->dtype.code == kDLUInt` as it is the same for both cases.

2024-09-18 23:53 UTC, AryanSalmanpour commented on src/roc_pyvideodecode.cpp
> +        std::vector<size_t> shape{ static_cast<size_t>(height * 1.5), static_cast<size_t>(width)};      //height is multiplied by 1.5 for interleaved YUV
change the `interleaved YUV` to `NV12 format` in the comment section.

2024-09-19 12:29 UTC, jeffqjiangNew approved these changes

2024-09-19 12:43 UTC, AryanSalmanpour approved these changes

2024-09-19 12:43 UTC, merged