Adding YUV separate tensors with all related code and python example
ROCm/rocPyDecode pull request #92
Opened 2024-09-21 01:37 UTC by essamROCm

Adding YUV separate tensors with all related code and python example and its documentation.
The python example shows how to use the new API and how to save Y or UV plane.

2024-09-22 00:33 UTC, LakshmiKumar23 approved these changes

2024-09-24 14:23 UTC, AryanSalmanpour requested changes

2024-09-24 14:23 UTC, AryanSalmanpour commented on samples/videodecodetorch_yuv.py
> +
Please also add code here to append the UV plane (i.e., packet.extBufYuv[1]) to the same file and rename the file from "_y_plane.yuv" to "_yuv_planes.yuv" so that both planes are saved into a single file for visual examination.

2024-09-24 14:23 UTC, AryanSalmanpour commented on samples/videodecodetorch_yuv.py
> +    mem_type = 1 if (mem_type < 0 or mem_type > 2) else mem_type
mem_type should be 0 by default.

2024-09-24 14:38 UTC, LakshmiKumar23 commented on src/roc_pyvideodecode.cpp
> +    SaveFrameToFile(output_file_name_in, (void *)surf_mem, surf_info, image_size);
can we club these two functions together? `PySaveTensorToFile` and `PySaveFrameToFile`and It calls the same SaveFrameToFile underneath. It can do the third check too, like it does for rgb vs plane now

2024-09-24 14:52 UTC, AryanSalmanpour requested changes

2024-09-24 14:52 UTC, AryanSalmanpour commented on src/roc_pyvideodecode.cpp
> +        if(SeparateYuvPlanes) {
formatting: change `if(SeparateYuvPlanes)` -> `if (SeparateYuvPlanes)`

2024-09-24 14:52 UTC, AryanSalmanpour commented on src/roc_pyvideodecode.cpp
> +            OutputSurfaceInfo * p_surf_info = reinterpret_cast<OutputSurfaceInfo*>(surface_info);
formatting: change` OutputSurfaceInfo * p_surf_info` ->` OutputSurfaceInfo* p_surf_info`

2024-09-24 14:52 UTC, AryanSalmanpour commented on src/roc_pyvideodecode.cpp
> +            if(p_surf_info->surface_format == rocDecVideoSurfaceFormat_NV12) {
formatting: add a space: `if(p_surf_info->surface_format == rocDecVideoSurfaceFormat_NV12)` -> `if (p_surf_info->surface_format == rocDecVideoSurfaceFormat_NV12)`

2024-09-24 14:52 UTC, AryanSalmanpour commented on src/roc_pyvideodecode.cpp
> +                std::vector<size_t> shape{ static_cast<size_t>(height/2), static_cast<size_t>(width)};
Add space: change `height/2` -> `height >> 1`

2024-09-24 14:52 UTC, AryanSalmanpour commented on src/roc_pyvideodecode.cpp
> +                uintptr_t u_offset = static_cast<uintptr_t>(height * width * ((bit_depth==8) ? sizeof(uint8_t) : sizeof(uint16_t))); // actual bytes/mem offset
Please use the `p_surf_info->output_pitch` * `p_surf_info->output_vstride` to get the correct uv_offset.

2024-09-24 14:52 UTC, AryanSalmanpour commented on src/roc_pyvideodecode.cpp
> +    if(rgb_format!=-1) { // -1 to calc YUV size
formatting: `rgb_format!=-1` -> `rgb_format != -1`

2024-09-24 14:52 UTC, AryanSalmanpour commented on src/roc_pyvideodecode.cpp
> +        image_size = width * height * ((bit_depth==8) ? sizeof(uint8_t) : sizeof(uint16_t));
formatting: `bit_depth==8` to `bit_depth == 8`

2024-09-24 17:10 UTC, essamROCm commented on samples/videodecodetorch_yuv.py
> +    mem_type = 1 if (mem_type < 0 or mem_type > 2) else mem_type
Done

2024-09-24 17:10 UTC, essamROCm commented on src/roc_pyvideodecode.cpp
> +    SaveFrameToFile(output_file_name_in, (void *)surf_mem, surf_info, image_size);
Done

2024-09-24 17:10 UTC, essamROCm commented on src/roc_pyvideodecode.cpp
> +        if(SeparateYuvPlanes) {
Done

2024-09-24 17:10 UTC, essamROCm commented on src/roc_pyvideodecode.cpp
> +            OutputSurfaceInfo * p_surf_info = reinterpret_cast<OutputSurfaceInfo*>(surface_info);
Done

2024-09-24 17:10 UTC, essamROCm commented on src/roc_pyvideodecode.cpp
> +            if(p_surf_info->surface_format == rocDecVideoSurfaceFormat_NV12) {
Done

2024-09-24 17:11 UTC, essamROCm commented on src/roc_pyvideodecode.cpp
> +                std::vector<size_t> shape{ static_cast<size_t>(height/2), static_cast<size_t>(width)};
Done

2024-09-24 17:11 UTC, essamROCm commented on src/roc_pyvideodecode.cpp
> +    if(rgb_format!=-1) { // -1 to calc YUV size
Done

2024-09-24 17:11 UTC, essamROCm commented on src/roc_pyvideodecode.cpp
> +        image_size = width * height * ((bit_depth==8) ? sizeof(uint8_t) : sizeof(uint16_t));
Done

2024-09-24 17:11 UTC, essamROCm commented on src/roc_pyvideodecode.cpp
> +                uintptr_t u_offset = static_cast<uintptr_t>(height * width * ((bit_depth==8) ? sizeof(uint8_t) : sizeof(uint16_t))); // actual bytes/mem offset
Done

2024-09-24 20:58 UTC, AryanSalmanpour approved these changes

2024-09-24 22:29 UTC, LakshmiKumar23 approved these changes

2024-09-24 23:07 UTC, merged