Create rocPyDecode Python distribution wheel
ROCm/rocPyDecode pull request #99
Opened 2024-09-27 06:24 UTC by essamROCm

**

> **Create a distribution wheel for rocPyDecode**

**

In order to create a distribution wheel for rocPyDecode, you must use the added script 'build_rocpydecode_wheel.py', as follow:

**-- on the rocPyDecode folder --:**
sudo python3 **build_rocpydecode_wheel.py**

**-- if previous attempt made, it is recommended to cleanup before running the script above, as follow:**
	sudo rm -rf build/
	sudo rm -rf dist/
	sudo rm -rf rocPyDecode.egg-info/
	sudo pip3 uninstall rocPyDecode -y
	#-- or if not used pip3 then: --
	pip3 uninstall rocPyDecode -y 
	# then create the wheel
	sudo python3 build_rocpydecode_wheel.py

**if the objective is NOT just to create the wheel but also to install it, add the following command:**
-- create the wheel
	sudo python3 build_rocpydecode_wheel.py
-- install it (assuming you are still on rocPyDecode folder)
	sudo pip3 install ./dist/rocPyDecode-1.0.0.60300-py3-none-manylinux_2_28_x86_64.whl
-- on any other folder just use the full path of where the wheel is:
	sudo pip3 install /full-path-wheel-location/rocPyDecode-1.0.0.60300-py3-none-manylinux_2_28_x86_64.whl

**-- The original method of building/installing the rocPyDecode still can be used** INSTEAD, but it is NOT needed if you create and install the wheel.
	sudo pip3 install . -v # not needed if already created and installed the wheel

**-- You can create the wheel and not install it, send it to the customer with instruction how to install it.**

**-- You can create the wheel and still install using the original method:**
	sudo pip3 install . -v 

**-- After installing via the WHEEL or via pip3 install . you can locate the .so file as follow:**
	sudo find / -name "rocPyDecode*.so"		# just to see it is there, this step is not needed for customers

**-- The wheel inclues now the "python samples", you can also locate them via:**	
	sudo find / -name "videodecodetorc*.py"

**-- The wheel content can be viewed as follow (assuming you are on the rocPyDecode folder):**
	**unzip** -l dist/rocPyDecode-1.0.0.60300-py3-none-manylinux_2_28_x86_64.whl

**-- The content look like this:**

essam@CV1:~/rocPyDecodePublic$ **unzip -l dist/rocPyDecode-1.0.0.60300-py3-none-manylinux_2_28_x86_64.whl**
Archive:  dist/rocPyDecode-1.0.0.60300-py3-none-manylinux_2_28_x86_64.whl
  Length      Date    Time    Name
     1135  2024-09-27 05:35   pyRocVideoDecode/__init__.py
     1798  2024-09-27 05:35   pyRocVideoDecode/__init__.pyi
     5744  2024-09-27 05:35   pyRocVideoDecode/decoder.py
     2020  2024-09-27 05:35   pyRocVideoDecode/demuxer.py
     3726  2024-09-27 05:35   pyRocVideoDecode/types.py
     9637  2024-09-27 05:35   samples/videodecode.py
     7856  2024-09-27 05:35   samples/videodecodemem.py
     5628  2024-09-27 05:35   samples/videodecodeperf.py
     5635  2024-09-27 05:35   samples/videodecodergb.py
     5461  2024-09-27 05:35   samples/videodecodetorch.py
     5772  2024-09-27 05:35   samples/videodecodetorch_resnet50.py
     6414  2024-09-27 05:35   samples/videodecodetorch_yuv.py
     1077  2024-09-27 05:42   rocPyDecode-1.0.0.60300.dist-info/LICENSE
      231  2024-09-27 05:42   rocPyDecode-1.0.0.60300.dist-info/METADATA
      110  2024-09-27 05:42   rocPyDecode-1.0.0.60300.dist-info/WHEEL
       25  2024-09-27 05:42   rocPyDecode-1.0.0.60300.dist-info/top_level.txt
     1448  2024-09-27 05:42   rocPyDecode-1.0.0.60300.dist-info/RECORD
    63717                     17 files

**_The creation of the wheel in this method is automated, just run the script, it will build rocPyDecode and creates its wheel without installing it. Installing it is an extra step, which is typically done as intended by the user/customer. The daily builds can use this method to create daily wheel for rocPyDecode._**

2024-09-27 14:21 UTC, LakshmiKumar23 commented
Added comments offline. This is still not adding the .so file to the wheel.

2024-09-27 17:22 UTC, rrawther commented
@essamROCm : It is still missing the rocpyDecode .so file without which it is not complete

2024-09-27 23:04 UTC, essamROCm commented
> @essamROCm : It is still missing the rocpyDecode .so file without which it is not complete

Hi @rrawther: 

I modified the code to make sure setup.py is actually building the .so and adding it to the wheel.
Please try it now, it creates the wheel and have the .so inside of it.
When you install the wheel, run any sample to make sure it works:
    _sudo pip3 install ./dist/name_of_the_wheel_file.whl_

2024-09-28 00:24 UTC, rrawther commented on CMakeLists.txt
> +    file(WRITE ./export_path "${ROCM_PATH}/include/rocdecode/\n" "${ROCM_PATH}/share/rocdecode/utils/\n" "${ROCM_PATH}/share/rocdecode/utils/rocvideodecode/\n" "${HIP_INCLUDE_DIRS}\n" "${pybind11_INC
instead of writing these paths in a separate file, why don't we use $(ROCM_PATH) env to derive the paths in setup.py directly

2024-09-28 00:30 UTC, rrawther commented on setup.py
> +with open('export_path', 'r') as file:
please use ENV ROCM_PATH to derive these relative paths instead of using a separate file. Also file reading can slow down the process and is un-necessary

2024-09-28 00:39 UTC, rrawther commented on setup.py
> +with open('export_path', 'r') as file:
please get rid of the extra file (export_path) and use environment variables (like ROCM_PATH, pybind11_INCLUDE_DIRS etc) to derive these paths.

2024-09-28 00:43 UTC, rrawther commented on setup.py
> +    include_dirs=[rocDecode_Headers,utils_folder,decoder_class_folder,HIP_Headers,pybind11_Headers],
do you really need HIP_headers and extra_compile_args here. I think we are not compiling any HIP kernels in rocPyDecode.

2024-09-28 00:47 UTC, rrawther commented on setup.py
> +    library_dirs=[rocm_path+'/lib/','/usr/local/lib/','/usr/lib/x86_64-linux-gnu/'],
why do we need /usr/local/xxx and /usr/lib/xxx here. It may not work in other OS's

2024-09-28 00:47 UTC, rrawther commented on setup.py
> +    libraries=['rocdecode','avcodec','avformat','avutil'])],
avcodec, avformat, avutil is already linked to rocdecode. Do we need here as well

2024-09-28 00:49 UTC, rrawther commented on setup.py
> +    [Extension('rocPyDecode',
better to define a separate class for this

2024-09-28 00:49 UTC, rrawther requested changes
Added review comments

2024-09-28 02:27 UTC, kiritigowda commented
@essamROCm - This PR creates a whl that can be exported into a docker and tested with the below instructions.


```
sudo apt install rocdecode-test
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
rocdecode-test is already the newest version (0.7.0.60300-crdnnh.14854~22.04).
0 upgraded, 0 newly installed, 0 to remove and 29 not upgraded.
root@simon:~# pip3 install --force-reinstall rocPyDecode-1.0.0.60300-cp310-cp310-manylinux_2_28_x86_64.whl --verbose
Using pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)
Processing ./rocPyDecode-1.0.0.60300-cp310-cp310-manylinux_2_28_x86_64.whl
Installing collected packages: rocPyDecode
  Attempting uninstall: rocPyDecode
    Found existing installation: rocPyDecode 1.0.0.60300
    Uninstalling rocPyDecode-1.0.0.60300:
      Removing file or directory /usr/local/lib/python3.10/dist-packages/pyRocVideoDecode/
      Removing file or directory /usr/local/lib/python3.10/dist-packages/rocPyDecode-1.0.0.60300.dist-info/
      Removing file or directory /usr/local/lib/python3.10/dist-packages/rocPyDecode.cpython-310-x86_64-linux-gnu.so
      Removing file or directory /usr/local/lib/python3.10/dist-packages/samples/
      Successfully uninstalled rocPyDecode-1.0.0.60300
Successfully installed rocPyDecode-1.0.0.60300
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@simon:~# python3 /usr/local/lib/python3.10/dist-packages/samples/videodecode.py -i /opt/rocm/share/rocdecode/video/AMD_driving_virtual_20-H265.mp4 

info: Input file: /opt/rocm/share/rocdecode/video/AMD_driving_virtual_20-H265.mp4
info: Using GPU device 0 - AMD Radeon PRO W6800[gfx1030] on PCI bus 11:0.0
info: decoding started, please wait! 

Input Video Information
	Codec        : H.265/HEVC
	Frame rate   : 30000/1001 = 29.97 fps
	Sequence     : Progressive
	Coded size   : [2048, 1024]
	Display area : [0, 0, 2048, 1024]
	Chroma       : YUV 420
	Bit depth    : 8
Video Decoding Params:
	Num Surfaces : 7
	Crop         : [0, 0, 2048, 1024]
	Resize       : 2048x1024

info: Total frame decoded: 601
info: avg decoding time per frame: 1.66 ms
info: avg frame per second: 600.61


```

2024-09-28 02:27 UTC, kiritigowda approved these changes

2024-09-28 02:35 UTC, kiritigowda commented
@essamROCm couple of improvements if you add in this same PR or create another after this is merged.

* Currently samples are located `/usr/local/lib/python3.10/dist-packages/samples/videodecode.py` -- change to `/usr/local/lib/python3.10/dist-packages/rocPyDecode/samples/videodecode.py` or place samples in `dist-packages/pyRocVideoDecode/`

2024-09-29 23:05 UTC, essamROCm commented on CMakeLists.txt
> +    file(WRITE ./export_path "${ROCM_PATH}/include/rocdecode/\n" "${ROCM_PATH}/share/rocdecode/utils/\n" "${ROCM_PATH}/share/rocdecode/utils/rocvideodecode/\n" "${HIP_INCLUDE_DIRS}\n" "${pybind11_INC
I looked into this, I discovered (according to what I read online) that CMake works on its own shell, not the global bash shell, so the method to use $ENV{} or use of ENV{MY_VAR}, etc. works within the execution of the CMakeList.txt but not showing to the global shell. I tried to use the $ENV{} and create variables or use the current cmake variables but they never appear at the setup.py level as their scope is only within the cmake. The use of temp txt file is safe and work OK for this purpose.

2024-09-29 23:07 UTC, essamROCm commented on setup.py
> +with open('export_path', 'r') as file:
please refer to my note above.

2024-09-29 23:07 UTC, essamROCm commented on setup.py
> +with open('export_path', 'r') as file:
please refer to my note above.

2024-09-29 23:08 UTC, essamROCm commented on setup.py
> +    include_dirs=[rocDecode_Headers,utils_folder,decoder_class_folder,HIP_Headers,pybind11_Headers],
We do compile the color kernel and the resize kernel, it is required here. The HIP path is required here.

2024-09-29 23:09 UTC, essamROCm commented on setup.py
> +    library_dirs=[rocm_path+'/lib/','/usr/local/lib/','/usr/lib/x86_64-linux-gnu/'],
I'll look int this, we may not need them.

2024-09-29 23:09 UTC, essamROCm commented on setup.py
> +    libraries=['rocdecode','avcodec','avformat','avutil'])],
Yes, if not linked here they will produce runtime error of missing functions, this is tried at runtime.

2024-09-29 23:10 UTC, essamROCm commented on setup.py
> +    [Extension('rocPyDecode',
I'll look into this. Will modify accordingly.

2024-09-29 23:13 UTC, essamROCm commented
> @essamROCm one quick improvement if you add in this same PR or create another after this is merged.
> 
> * Currently samples are located `/usr/local/lib/python3.10/dist-packages/samples/videodecode.py` -- change to `/usr/local/lib/python3.10/dist-packages/rocPyDecode/samples/videodecode.py` or place samples in `dist-packages/pyRocVideoDecode/`

@kiritigowda 
Hi Kiriti, thank you for reviewing this PR. I actually tried that, couldn't figure it out, to specifically use the python path, so I will keep trying to find a solution to that, so whether move it to python path or eventually the pyRocVideoDecode path.

2024-09-29 23:39 UTC, essamROCm commented on setup.py
> +    library_dirs=[rocm_path+'/lib/','/usr/local/lib/','/usr/lib/x86_64-linux-gnu/'],
OK, I removed them in the latest commit: https://github.com/ROCm/rocPyDecode/pull/99/commits/17abd945bf6ef024aab31d73571306c13b35812e

2024-09-29 23:40 UTC, essamROCm commented on setup.py
> +    [Extension('rocPyDecode',
Defined separately here in the latest commit: https://github.com/ROCm/rocPyDecode/pull/99/commits/17abd945bf6ef024aab31d73571306c13b35812e

2024-09-30 20:11 UTC, rrawther commented on CMakeLists.txt
> +    file(WRITE ./export_path "${ROCM_PATH}/include/rocdecode/\n" "${ROCM_PATH}/share/rocdecode/utils/\n" "${ROCM_PATH}/share/rocdecode/utils/rocvideodecode/\n" "${HIP_INCLUDE_DIRS}\n" "${pybind11_INC
can't u use ROCM_PATH similar to 
https://github.com/ROCm/rocAL/blob/develop/rocAL_pybind/setup.py

2024-09-30 20:12 UTC, rrawther approved these changes

2024-09-30 22:42 UTC, LakshmiKumar23 approved these changes

2024-09-30 22:42 UTC, merged